#!/usr/bin/env bash
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

PATH=$PATH:$HOME/bin:$HOME/.local/bin:bin
EDITOR="emacs -nw"

if [ "$PS1" != "" ]; then
    unset SSH_ASKPASS
    HISTFILESIZE=100000
    HISTCONTROL="ignoreboth"
    alias more=less
    shopt -s histappend
    PROMPT_COMMAND='history -a'
    bind "set completion-query-items 1000"
    HOSTNAME=`hostname -f 2>/dev/null`
    PS1="\e[0;34m[\$? \D{%b %d %H:%M:%S}] \u@$HOSTNAME\e[0;32m:\w\e[m \n\$ "
    LS_OPTIONS='--color=auto --quoting-style=shell'

    cd $(dirname $(dirname $(dirname "$(readlink ~/.bash_profile)")))
    $(bin/acr_compl -install)
    cd - >/dev/null
fi

# acr_compl -install needs a list of executables to work
# so it cannot be invoked until we switch to a particular directory
function beginwork() {
    cd "$1"
    $(acr_compl -install)
}

# export section
export PS1
export LS_OPTIONS
export PATH
export EDITOR
export HISTFILESIZE
export HISTCONTROL
export PROMPT_COMMAND
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export TERM=xterm-256color
