#!/usr/bin/env bash
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

PATH=$PATH:$HOME/bin:$HOME/.local/bin:bin
EDITOR="emacs -nw"

if [ "$PS1" != "" ]; then
    unset SSH_ASKPASS
    HISTFILESIZE=100000
    HISTCONTROL="ignoreboth"
    alias more=less
    shopt -s histappend
    PROMPT_COMMAND='history -a'
    bind "set completion-query-items 1000"
    HOSTNAME=`hostname -f 2>/dev/null`
    PS1="\e[0;34m[\$? \D{%b %d %H:%M:%S}] \u@$HOSTNAME\e[0;32m:\w\e[m \n\$ "
    LS_OPTIONS='--color=auto --quoting-style=shell'
    $(acr_compl -install 2>/dev/null)
fi
    
# export section
export PS1
export LS_OPTIONS
export PATH
export EDITOR
export HISTFILESIZE
export HISTCONTROL
export PROMPT_COMMAND
