name: Setup Developer Tools
description: Installs required developer tools and libraries
runs:
  using: "composite"
  steps:
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y \
          mariadb-client \
          mariadb-server \
          libmariadb-dev \
          libmariadbd-dev \
          libssl-dev \
          libcurl4-openssl-dev \
          liblz4-dev \
          llvm \
          cppcheck \
          valgrind
    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install \
          mariadb \
          openssl \
          curl \
          lz4 \
          llvm \
          cppcheck
