// Copyright (C) 2023-2026 AlgoRND
// Copyright (C) 2020-2023 Astra
// Copyright (C) 2013-2019 NYSE | Intercontinental Exchange
//
// License: GPL
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Contacting ICE: <https://www.theice.com/contact>
// Target: atf_ci (exe) -- Normalization tests (see citest table)
// Exceptions: yes
// Source: cpp/atf_ci/main.cpp
//

#include "include/atf_ci.h"
#include "include/lib_git.h"

// -----------------------------------------------------------------------------

static strptr CurCitest() {
    return atf_ci::_db.c_citest ? strptr(atf_ci::_db.c_citest->citest) : strptr();
}

// -----------------------------------------------------------------------------

bool atf_ci::CaptureQ() {
    return atf_ci::_db.cmdline.capture
        || (atf_ci::_db.c_citest
            && atf_ci::_db.c_citest->cijob == atf_ci::atfdb_cijob_normalize);
}

// -----------------------------------------------------------------------------

// Compare the current `git ls-files -m` snapshot against the previous
// one stored in atf_ci::_db.modfiles, report any newly-modified files,
// and update atf_ci::_db.modfiles to the current snapshot.  Without
// this delta, every test after the first dirtying one reports the
// same pre-existing dirt and gets charged for it.
// Return TRUE if no new modifications.  On drift, also set exit_code
// (like CheckNoDir) so a caller that discards the return -- e.g. a
// sandboxed citest whose per-test gate is skipped -- still fails the run.
bool atf_ci::CheckCleanDirs() {
    bool ret=true;
    tempstr after = lib_git::GitModifiedFiles(".");
    tempstr added;
    ind_beg(algo::Line_curs,line,after) {
        bool seen=false;
        ind_beg(algo::Line_curs,prev,_db.modfiles) {
            if (prev == line) { seen=true; break; }
        }ind_end;
        if (!seen) {
            added << line << eol;
        }
    }ind_end;
    if (added != "") {
        prerr("atf_ci.modified_files"
              <<Keyval("during",CurCitest())
              <<Keyval("files",Trimmed(added))
              <<Keyval("success","N")
              <<Keyval("comment","Please resolve modified files and try again"));
        prerr("Some of the diffs are shown below");
        SysCmd("git diff | head -500");
        algo_lib::_db.exit_code=1;
        ret=false;
    }
    _db.modfiles = after;
    return ret;
}

// Check that DIR is not generated by the test
void atf_ci::CheckNoDir(strptr dir) {
    if (algo_lib::_db.exit_code==0) {
        if (algo::DirectoryQ(dir)) {
            prerr("atf_ci.modified_files"
                  <<Keyval("during",CurCitest())
                  <<Keyval("dir",dir)
                  <<Keyval("success","N")
                  <<Keyval("comment","Please check generated dir and try again"));
            algo_lib::_db.exit_code=1;
        }
    }
}

algo::UnTime atf_ci::FileAtime(algo::strptr fname) {
    struct stat st;
    algo::UnTime ret;
    if (stat(Zeroterm(tempstr()<<fname),&st)==0) {
        ret = algo::ToUnTime(algo::UnixTime(st.st_atime));
    }
    return ret;
}

// Return max. access time of all files in directory DIRNAME, as recursively
// calculated. This is different from the directory access time.
algo::UnTime atf_ci::DirAtime(algo::strptr dirname) {
    algo::UnTime ret;
    ind_beg(algo::Dir_curs,entry,DirFileJoin(dirname,"*")) {
        if (entry.is_dir) {
            i64_UpdateMax(ret.value,DirAtime(entry.pathname).value);
        } else {
            i64_UpdateMax(ret.value,FileAtime(entry.pathname).value);
        }
    }ind_end;
    return ret;
}

// -----------------------------------------------------------------------------

// SIGALRM handler: the running citest exceeded atf_ci.FCitest.timeout.  An
// in-process step cannot be unwound to continue, so name the offending citest
// and exit 124.  Mirrors algo's fatal-signal handler: compose into _db.fatalerr
// and emit with a single write(), never prerr.
static void CitestTimeout(int) {
    algo_lib::_db.fatalerr << "atf_ci.timeout"
                           <<Keyval("citest", CurCitest())
                           <<Keyval("comment", "citest exceeded its timeout budget") << eol;
    algo::strptr msg = algo_lib::_db.fatalerr;
    ssize_t n = write(2, msg.elems, msg.n_elems);
    (void)n;
    _exit(124);
}

// -----------------------------------------------------------------------------

static bool RunCiTest(atf_ci::FCitest &citest) {
    prlog("atf_ci.begin"
          <<Keyval("citest",citest.citest)
          <<Keyval("sandbox",citest.sandbox));
    algo::UnTime start=algo::CurrUnTime();
    // enter sandbox, if requested
    if (citest.sandbox) {
        command::wt_proc wt;
        wt.cmd.name.expr = dev_Sandbox_sandbox_atf_ci;
        if (bool_Update(atf_ci::_db.sandbox_need_init,true)) {
            wt.cmd.reset = true;// initialize
        } else {
            wt.cmd.clean = true;// quick reset
        }
        wt_ExecX(wt);
        algo_lib::PushDir(algo_lib::WtDir(dev_Sandbox_sandbox_atf_ci));
    }
    // a coverage citest writes its .gcda into its own dir; GCC_PROFILE_DIR is
    // resolved at runtime by every coverage-built binary and inherited down
    // the whole spawn tree, so cov_finalize can merge the per-citest dirs.
    // Absolute path -- subprocesses chdir into tempdirs / the sandbox.
    bool cov = citest.cijob == atf_ci::atfdb_cijob_coverage;
    if (cov) {
        tempstr covdir = tempstr() << "temp/cov/" << citest.citest << ".d";
        algo::RemDirRecurse(covdir, true);
        algo::CreateDirRecurse(covdir);
        setenv("GCC_PROFILE_DIR", Zeroterm(GetFullPath(covdir)), 1);
    }
    // Cap the step at the citest's timeout: alarm() arms SIGALRM, whose handler
    // (CitestTimeout, installed in Main) reports the offending citest and exits.
    // The step runs in-process -- it cannot be unwound to continue, so a timeout
    // ends the whole run; the surviving non-timeout path keeps the original
    // exit_code/ErrorX accounting and modfiles/gcov behavior.  Disarm afterwards
    // so the alarm cannot fire during CheckCleanDirs or the next citest's setup.
    atf_ci::_db.c_citest = &citest;
    if (citest.timeout > 0) {
        alarm(citest.timeout);
    }
    try {
        int code_before = algo_lib::_db.exit_code;
        citest.step();
        citest.nerr += code_before == 0 && algo_lib::_db.exit_code != 0;
    } catch (algo_lib::ErrorX &x) {
        citest.nerr++;
        prlog(x.str);
    }
    alarm(0);
    if (cov) {
        unsetenv("GCC_PROFILE_DIR");
    }
    // for sandboxed tests, do not check for modified files;
    // for regular tests, compare the post-test git-modified set with
    // _db.modfiles (set at startup or end of the previous test) and
    // charge this test only with NEW lines in the diff.  Without the
    // delta, every test after the first dirtying one would see the
    // same pre-existing dirt and get charged for it.
    if (!citest.sandbox && atf_ci::_db.cmdline.check_clean) {
        citest.nerr += !atf_ci::CheckCleanDirs();
    }
    if (citest.nerr) {
        algo_lib::_db.exit_code = 1;
    }
    if (citest.sandbox) {
        algo_lib::PopDir();
    }
    prlog("atf_ci.citest"
          <<Keyval("citest",citest.citest)
          <<Keyval("runtime", algo::CurrUnTime()-start)
          <<Keyval("success", Bool(citest.nerr==0))
          <<Keyval("comment",citest.comment));
    return citest.nerr==0;
}

// -----------------------------------------------------------------------------

// Compare contents of file `outfname` with the reference file.
// Any difference = error
void atf_ci::CompareOutput(strptr outfname) {
    tempstr expect_fname = tempstr() << "test/atf_ci/" << atf_ci::_db.c_citest->citest;
    if (CaptureQ()) {
        CopyFileX(outfname, expect_fname, 0644);
    } else {
        vrfy_(SysCmd(tempstr()
                     << "git --no-pager diff --no-index "
                     << " " << expect_fname
                     << " " << outfname) == 0);
    }
}


// -----------------------------------------------------------------------------

// Run the citests the cmdline selects, and report the run.
static void RunCijob() {
    // Each citest is capped at its atfdb.Citest.timeout via alarm() in RunCiTest.
    signal(SIGALRM, CitestTimeout);

    // Release the AMS shared-memory segments that no longer have an owner,
    // before any test spawns one of its own.  A segment outlives the process
    // that created it, since only shm_unlink removes one, so a run that ended
    // abruptly leaves its segments behind, and they accumulate until shm is
    // exhausted and every later shm/spawn/connect test fails.
    //
    // Unlinking a segment whose writer is already gone cannot disturb anything
    // that is running, which is why this runs everywhere -- on a developer host
    // as much as on a CI runner.  Killing the processes that still hold
    // segments is the other half of the same reclamation, and it cannot be
    // scoped that way: a developer host carries several worktrees of this repo
    // at once, each running its own atf_ci, and lock/atf_ci is a per-checkout
    // path, so it serializes runs within a worktree and not across them.  An
    // unscoped kill there means one worktree's normalize kills the cluster
    // another session is measuring, and the victim observes only that its
    // process disappeared.  So the kill belongs where a predecessor's orphans
    // are the only processes that can be present, which is a CI runner between
    // two jobs, and bin/ci-reap performs it there from before_script.
    SysCmd("amsspy -clean", algo::FailokQ(true));

    // With -check_clean, refuse to start when the working tree is
    // already dirty: subsequent tests may overwrite the user's
    // modified files and destroy their work.  Otherwise the empty
    // baseline guarantees per-test delta detection is exact.
    if (atf_ci::_db.cmdline.check_clean) {
        tempstr dirty = lib_git::GitModifiedFiles(".");
        vrfy(dirty=="", tempstr()
             <<"atf_ci.dirty_tree"
             <<Keyval("files",Trimmed(dirty))
             <<Keyval("comment","-check_clean refuses to run on a dirty tree; commit or stash first"));
    }

    int n_run  = 0;
    int n_pass = 0;
    ind_beg(atf_ci::_db_citest_curs,citest,atf_ci::_db) {
        if (Regx_Match(atf_ci::_db.cmdline.citest, citest.citest)
            && Regx_Match(atf_ci::_db.cmdline.cijob, citest.cijob)) {
            ++n_run;
            bool ok = RunCiTest(citest);
            n_pass += ok;
            // -maxerr sets the run's error budget (collect-all under
            // normalize); a failfast citest overrides it -- its failure is
            // conclusive on its own (a perf gate miss needs no corroboration
            // from the remaining tests), so the run reports immediately
            // instead of spending the rest of the job's runtime.
            if (!ok && citest.failfast) {
                prlog("atf_ci.failfast"
                      <<Keyval("citest",citest.citest)
                      <<Keyval("comment","failfast citest failed; skipping remaining citests"));
                break;
            }
            if (n_run-n_pass > atf_ci::_db.cmdline.maxerr) {
                break;
            }
        }
    }ind_end;

    if (n_run==0) {
        algo_lib::_db.exit_code=1;
        prlog("atf_ci.nomatch"
              <<Keyval("citest",atf_ci::_db.cmdline.citest)
              <<Keyval("comment","no tests matched specified pattern. run 'acr citest' to see the full list, or see the list below"));
        SysCmd("acr citest | ssimfilt -t atfdb.%");
    }

    if (algo_lib::_db.exit_code != 0) {
        ind_beg(atf_ci::_db_citest_curs,citest,atf_ci::_db) {
            if (citest.nerr) {
                prlog("atf_ci.failed"
                      <<Keyval("citest",citest.citest)
                      <<Keyval("success",Bool(false))
                      <<Keyval("comment","See prior output for more information"));
            }
        }ind_end;
    }

    prlog("report.atf_ci"
          <<Keyval("n_citest", atf_ci::citest_N())
          <<Keyval("n_run", n_run)
          <<Keyval("n_pass", n_pass)
          <<Keyval("success", Bool(algo_lib::_db.exit_code==0))
          <<Keyval("comment",(algo_lib::_db.exit_code==0
                              ? "The coast is clear. Proceed with caution :-)"
                              : "Did not pass. Please resolve issues and try again.")));
}

// Two modes: -cleanup removes the credentials this checkout installed, and
// anything else runs the selected citests.
//
// The scrub takes none of the citest prologue, and -check_clean is the reason
// that matters.  A run of the tests refuses to start on a dirty tree, because a
// test may then overwrite work the operator has not committed.  The scrub reads
// its own record under temp/ and writes nothing to the tree, so the same refusal
// would only mean that a job which modified the tree -- which is most of them --
// leaves its credential behind on the runner.  Both modes take the lockfile, so
// a scrub cannot land while a run that installed a credential is still using it.
void atf_ci::Main() {
    algo_lib::DieWithParent();
    algo_lib::FLockfile lockfile;
    LockFileInit(lockfile, "lock/atf_ci");// prevent overlapping runs

    lib_ctype::Init();

    RunCijob();
}
