// Copyright (C) 2023-2026 AlgoRND
// Copyright (C) 2018-2019 NYSE | Intercontinental Exchange
//
// License: GPL
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Contacting ICE: <https://www.theice.com/contact>
// Target: amc (exe) -- Algo Model Compiler: generate code under include/gen and cpp/gen
// Exceptions: yes
// Source: cpp/amc/outfile.cpp -- Output functions
//

#include "include/amc.h"

// -----------------------------------------------------------------------------

// Insert comment
static void InsertComment(cstring &out, strptr text) {
    ind_beg(Line_curs,line,text) {
        out<<"//";
        if (ch_N(line)) {
            out<<" "<<line;
        }
        out<<eol;
    }ind_end;
}

// -----------------------------------------------------------------------------

// Write output file to disk
// and deallocate memory associated with it
void amc::gen_ns_write() {
    amc::FNs &ns=*amc::_db.c_ns;
    // A generation error must suppress all output: a partial write would
    // leave a half-regenerated tree that looks up to date. But exit_code
    // alone cannot serve as the gate: each failed write below increments it
    // too, so the first namespace's failed write would silently skip every
    // later namespace's writes, and the error report would name only the
    // first namespace's paths. Generation is complete when this phase runs
    // (ns_write is the last per-namespace gen), so exit_code counts pure
    // generation errors exactly until the first write -- capture it then,
    // and gate every namespace's output on the captured value.
    if (_db.n_generr == -1) {
        _db.n_generr = algo_lib::_db.exit_code;
    }
    // -derive writes the amc-owned tables and no source.  A gstatic that
    // carries one of those tables is compiled from the table's ssim file,
    // which is read back near the start of the run, so a run whose
    // derivation changes such a table generates its source from the file as
    // it stood before the change.  Deriving in a run of its own leaves the
    // files correct for the run that generates from them.
    if (!amc::QueryModeQ() && ch_N(amc::_db.cmdline.out_dir) && !amc::_db.cmdline.derive && _db.n_generr==0) {
        int nbefore=algo_lib::_db.stringtofile_nwrite;
        ind_beg(amc::ns_c_outfile_curs, outfile,ns) {
            amc::_db.report.n_cppfile++;
            // save to preassigned filename, or out dir if overridden.
            // a write that fails (missing directory, permission) fails the
            // run: exiting 0 with the generated code silently missing would
            // leave a stale tree that looks up to date
            tempstr fname(DirFileJoin(amc::_db.cmdline.out_dir, outfile.outfile));
            if (!algo::SaveFile(outfile.text, fname, "amc.outfile_write", "output file could not be written")) {
                algo_lib::_db.exit_code++;
            }
            frep_(i,ch_N(outfile.text)) {
                amc::_db.report.n_cppline += ch_qFind(outfile.text, i) == '\n';
            }
        }ind_end;
        amc::_db.report.n_filemod += algo_lib::_db.stringtofile_nwrite - nbefore;
        c_outfile_Cascdel(ns);
        ns.inl=NULL;
        ns.hdr=NULL;
        ns.cpp=NULL;
    }
}

// -----------------------------------------------------------------------------

// Create outfile record for specified filename
// T here is one outfile per generated output file
amc::FOutfile &amc::outfile_Create(strptr filename) {
    amc::FOutfile &outfile = amc::outfile_Alloc();
    outfile.outfile=filename;
    (void)outfile_XrefMaybe(outfile);
    strptr license = outfile.p_ns->p_license->text;
    if (!ch_N(outfile.text)) {
        cstring comment = tempstr()
            << eol
            << filename << eol
            << "Generated by AMC" << eol
            << eol
            << _db.copyright
            << eol
            << license;
        InsertComment(outfile.text,comment);
        outfile.text << eol << eol;
    }
    return outfile;
}
