// Copyright (C) 2023-2026 AlgoRND
// Copyright (C) 2023 Astra
// Copyright (C) 2017-2019 NYSE | Intercontinental Exchange
//
// License: GPL
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Contacting ICE: <https://www.theice.com/contact>
// Target: atf_ci (exe) -- Normalization tests (see citest table)
// Exceptions: yes
// Header: include/atf_ci.h
//

#include "include/algo.h"
#include "include/gen/atf_ci_gen.h"
#include "include/gen/atf_ci_gen.inl.h"

#include "include/lib_ctype.h"

namespace atf_ci { // update-hdr
    // Dear human:
    //     Text from here to the closing curly brace was produced by scanning
    //     source files. Editing this text is futile.
    //     To refresh the contents of this section, run 'update-hdr'.
    //     To convert this section to a hand-written section, remove the word 'update-hdr' from namespace line.

    // -------------------------------------------------------------------
    // cpp/atf_ci/abt_md.cpp
    //

    // Runs in sandbox
    //     (user-implemented function, prototype is in amc-generated header)
    // void citest_abt_md_after_ssimfile_is_added(); // gstatic/atfdb.citest:abt_md_after_ssimfile_is_added

    // -------------------------------------------------------------------
    // cpp/atf_ci/acr_ed.cpp
    //

    // Runs in sandbox
    //     (user-implemented function, prototype is in amc-generated header)
    // void citest_acr_ed_ssimdb(); // gstatic/atfdb.citest:acr_ed_ssimdb

    // Runs in sandbox
    // void citest_acr_ed_unittest(); // gstatic/atfdb.citest:acr_ed_unittest

    // Runs in sandbox
    // void citest_acr_ed_ssimfile(); // gstatic/atfdb.citest:acr_ed_ssimfile

    // Runs in sandbox
    // void citest_acr_ed_target(); // gstatic/atfdb.citest:acr_ed_target

    // -------------------------------------------------------------------
    // cpp/atf_ci/apm.cpp
    //
    //     (user-implemented function, prototype is in amc-generated header)
    // void citest_apm(); // gstatic/atfdb.citest:apm
    // void citest_apm_check(); // gstatic/atfdb.citest:apm_check
    // void citest_apm_reinstall(); // gstatic/atfdb.citest:apm_reinstall

    // -------------------------------------------------------------------
    // cpp/atf_ci/bootstrap.cpp
    //

    // Create a bootstrap file for each build dir
    //     (user-implemented function, prototype is in amc-generated header)
    // void citest_bootstrap(); // gstatic/atfdb.citest:bootstrap

    // -------------------------------------------------------------------
    // cpp/atf_ci/cppcheck.cpp
    //

    // Run static code analyzer
    // Check Linux only
    //     (user-implemented function, prototype is in amc-generated header)
    // void citest_cppcheck(); // gstatic/atfdb.citest:cppcheck

    // -------------------------------------------------------------------
    // cpp/atf_ci/main.cpp
    //

    // Check that a list of directories specified with DIRS is clean
    // Nothing is done if an error exit code is already set, since
    // this error might have been caused by the previous error.
    // Return TRUE if test succeeds
    bool CheckCleanDirs(strptr dirs);

    // Check that DIR is not generated by the test
    void CheckNoDir(strptr dir);
    //     (user-implemented function, prototype is in amc-generated header)
    // void citest_atf_amc(); // gstatic/atfdb.citest:atf_amc
    // void citest_atf_unit(); // gstatic/atfdb.citest:atf_unit
    // void citest_atf_comp(); // gstatic/atfdb.citest:atf_comp
    // void citest_atf_comp_cov(); // gstatic/atfdb.citest:atf_comp_cov
    // void citest_atf_comp_mem(); // gstatic/atfdb.citest:atf_comp_mem
    // void citest_normalize_amc_vis(); // gstatic/atfdb.citest:normalize_amc_vis
    // void citest_gitfile(); // gstatic/atfdb.citest:gitfile
    algo::UnTime FileAtime(algo::strptr fname);

    // Return max. access time of all files in directory DIRNAME, as recursively
    // calculated. This is different from the directory access time.
    algo::UnTime DirAtime(algo::strptr dirname);

    // Delete files that haven't been accessed in the last couple days
    //     (user-implemented function, prototype is in amc-generated header)
    // void citest_cleantemp(); // gstatic/atfdb.citest:cleantemp
    // void citest_scanreadme(); // gstatic/atfdb.citest:scanreadme
    // void citest_quickreadme(); // gstatic/atfdb.citest:quickreadme

    // Compare contents of file `outfname` with the reference file.
    // Any difference = error
    void CompareOutput(strptr outfname);
    //     (user-implemented function, prototype is in amc-generated header)
    // void citest_bintests(); // gstatic/atfdb.citest:bintests
    // void citest_checkclean(); // gstatic/atfdb.citest:checkclean
    // void citest_lineendings(); // gstatic/atfdb.citest:lineendings
    // void citest_shebang(); // gstatic/atfdb.citest:shebang
    // void citest_comptest(); // gstatic/atfdb.citest:comptest
    // void citest_readme(); // gstatic/atfdb.citest:readme
    // void Main(); // main:atf_ci

    // -------------------------------------------------------------------
    // cpp/atf_ci/src.cpp -- source file (cpp/, include/) normalizations including amc
    //

    // indent any source files modified in the last commit
    // indentation under CYGWIN is broken -- and we don't have a cross-platform
    // solution. so only try it on Linux
    //     (user-implemented function, prototype is in amc-generated header)
    // void citest_indent_srcfile(); // gstatic/atfdb.citest:indent_srcfile
    // void citest_update_script(); // gstatic/atfdb.citest:update_script

    // indent all script files modified in the last commit
    // void citest_indent_script(); // gstatic/atfdb.citest:indent_script

    // update file headers
    // void citest_file_header(); // gstatic/atfdb.citest:file_header

    // source code police
    // void citest_src_lim(); // gstatic/atfdb.citest:src_lim

    // run amc
    // void citest_amc(); // gstatic/atfdb.citest:amc
    // void citest_tempcode(); // gstatic/atfdb.citest:tempcode
    // void citest_stray_gen(); // gstatic/atfdb.citest:stray_gen
    // void citest_encoding(); // gstatic/atfdb.citest:encoding
    // void citest_iffy_src(); // gstatic/atfdb.citest:iffy_src
    // void citest_non_copyrighted(); // gstatic/atfdb.citest:non-copyrighted

    // -------------------------------------------------------------------
    // cpp/atf_ci/ssim.cpp -- ssim database normalizations
    //
    //     (user-implemented function, prototype is in amc-generated header)
    // void citest_normalize_acr(); // gstatic/atfdb.citest:normalize_acr
    // void citest_normalize_acr_my(); // gstatic/atfdb.citest:normalize_acr_my
    // void citest_ssimfile(); // gstatic/atfdb.citest:ssimfile
}
